# Generated by Django 2.0 on 2018-05-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('baths', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sqft', models.IntegerField(default=0)),
            ],
        ),
    ]
